import simulation


model = simulation.Network(prov_data, sei_data, com_areas_boundaries, distances)

model.gen_adjacency_graph()

# In this point, we have what we need for the dashboard: the graph and the table

# We have to allow for the user to choose, and the graphs and tables will be generated by the function simulation.ui_shock()